---
title: Inecuaciones
title-block-banner: true
lang: es
execute:
  echo: false
format: 
  html: 
    include-in-header: includes-header.html
    toc: true
    page-layout: full
    format-links: true
---

Las inecuaciones son expresiones algebraicas relacionadas no por la igualdad ($=$) como en las ecuaciones, sino por desigualdades representadas con los símbolos "$\le$", "$\ge$", "$<$" o "$>$".

Las inecuaciones con solución pueden tener un número finito o infinito de soluciones. El proceso para resolverlas es similar al que se sigue para resolver una ecuación, siendo cuidadoso con las reglas de cálculo cuando aparecen desigualdades. Por ejemplo, por destacar una de estas reglas, si en algún momento de la resolución es preciso multiplicar o dividir ambos miembros de la inecuación por un número negativo, recordamos que la desigualdad se invierte.

## Inecuaciones lineales con una incógnita

Son las inecuaciones más sencillas que se nos pueden presentar.

Vamos a resolver la inecuación $2x+5 \ge x-5$.

$$
\begin{aligned}
2x+5 & \ge x-5, \\
%\intertext{pasamos la $x$ del miembro izquierdo a la derecha, y los coeficientes independientes los dejamos a la izquierda}
2x-x & \ge -5-5, \\
x &\ge -10.\end{aligned}
$$

Por tanto la solución de la inecuación son todos los números reales que verifican ser mayores o iguales a -10, es decir, las soluciones se encuentran en el intervalo $[-10,+\infty)$.


::: {#exr-1}

1.  Resuelve la inecuación $4x-5 < 7x+8$.
    <button id="e1-1" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e1-1 .collapse}
    La solución es $x >\dfrac{-13}{3}$.
    :::

2.  Resuelve la inecuación $2(-x+5)-(6+x)>4+2(x-3)$, y razona si los números $-3, -1, 0$ y $ 1$ son solución de la misma.
    <button id="e1-2" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e1-2 .collapse}
    La solución es $x <\dfrac{6}{5}$. Todos los números dados son solución de la inecuación.
    :::

3.  Ídem al ejercicio anterior con la inecuación $\dfrac{3x}{5}-\dfrac{11x}{10} \ge 1-\dfrac{6-x}{4}$.
    <button id="e1-3" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e1-3 .collapse}
    Solución: $x \leq\dfrac{2}{3}$.
    :::

4.  Resuelve $(x+1)^2-(x-1)^2+12 \ge 0$.
    <button id="e1-4" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e1-4 .collapse}
    La solución es $x \ge -3$.
    :::
:::

## Sistemas lineales de dos inecuaciones con una incógnita

Vamos a plantear ahora sistemas de dos inecuaciones lineales con una incógnita. Veremos que las soluciones, si hay más de una, son infinitas.

Consideremos el sistema 

$$
\left\{
\begin{aligned} x-3 &>0, \\
2x & < 8.
\end{aligned}
\right.
$$

Para resolverlo, resolvemos cada inecuación de forma independiente. 

$$
\Biggr\{
\begin{aligned}
x & >3, \\
x & <4,
\end{aligned}
$$ 

con lo que la solución es $3 < x <4$. Es decir, las soluciones de este sistema son todos los números reales que están en el intervalo $(3,4)$.

Hay que tener en cuenta que un sistema de inecuaciones de este tipo puede tener solución (sistema compatible) o puede no tenerlo (sistema incompatible).

::: {#exr-2}

Resuelve los siguientes sistemas de inecuaciones.


1.  $\Biggr\{ \begin{aligned} 3x-6 & \ge 9, \\ 4-x & < -5. \end{aligned}$
    <button id="e2-1" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e2-1 .collapse}
    Solución: $x > 9$.
    :::

2.  $\Biggr\{ \begin{aligned} 3x-6 & \le 9 \\ 4-x & < -5. \end{aligned}$
    <button id="e2-2" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e2-2 .collapse}
    Este sistema no tiene solución.
    :::

3.  $\Biggr\{ \begin{aligned} 8x+7 & < 16-x, \\ -3x+5 & >2x. \end{aligned}$
    <button id="e2-3" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e2-3 .collapse}
    Solución: $x<1$.
    :::
:::


## Inecuaciones de segundo grado

También podemos plantear y resolver inecuaciones que involucren un polinomio de grado 2; esto es, una inecuación del tipo $P(x) \le Q(x)$, o, $P(x) <Q(x)$, donde ambas expresiones, $P$ y $Q$, son polinomios de grado 2. Para resolverlas, simplificamos coeficientes hasta conseguir una inecuación de 2º grado comparada con el cero. Después factorizamos el polinomio resultante (utilizando la resolución de una ecuación de 2º grado) y discutimos casos. Vemos todo este proceso con un ejemplo:

Consideramos la inecuación: $x^2-3x-3<-4x-1$. Pasamos todos los coeficientes a un miembro, por ejemplo al izquierdo y nos queda:

$$\begin{aligned}
x^2-3x+4x-3+1 & <0 ,\\
x^2+x-2&<0, \\
%\intertext{factorizamos el polinomio resolviendo la ecuación $x^2+x-2=0$}
(x+2)(x-1) &<0.\end{aligned}
$$

Llegados a este punto, discutimos casos para encontrar la solución de la inecuación.

$$
\begin{aligned}
\text{Si} \ x < -2, & \hbox{ entonces } \ (x+2)(x-1)>0. \\
\text{Si} \ -2 < x <1, & \hbox{ entonces } \ (x+2)(x-1)<0. \\
\text{Si} \ x > 1, & \hbox{ entonces } \ (x+2)(x-1)>0. \end{aligned}
$$

Por tanto, la solución de la inecuación la forman los números $x$, que verifican $-2<x<1$, es decir, el intervalo $(-2,1)$.

Podemos dibujar la parábola $y=x^2+x-2$ y ver gráficamente la solución.

::: {#box .jxgbox style="width:500px; height:500px;margin:auto;"}
:::

```{ojs}
board = JXG.JSXGraph.initBoard('box', {boundingbox: [-4, 4, 4, -4], axis:true, showCopyright:false, showNavigation:false});
curve = board.create('functiongraph', [function(t){ return(t*t+t-2)}, -10,10]);

p1 = board.create('point', [-20.0, 0.0]);
p2 = board.create('point', [20.0, 0.0]);
l1 = board.create('line', [p1, p2], {visible:false});

i = board.create('intersection', [curve, l1, 0],{withLabel:false});
j = board.create('intersection', [curve, l1, 1],{withLabel:false});
s = board.create("segment", [i,j]);
```


::: {#exr-3}

Resolver cada una de las inecuaciones siguientes:

1.  $x^2+2x+4\ge 2x+5$.
    <button id="e3-1" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e3-1 .collapse}
    Solución: $x\le -1$ o $x\ge 1$.
    :::

2.  $16x-x^2\ge 16$.
    <button id="e3-2" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e3-2 .collapse}
    Solución: $4(2-\sqrt{3})\le x\le 4(2+\sqrt{3})$.
    :::

3.  $2x^2-2x+9\le x^2-5x+7$.
    <button id="e3-3" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e3-3 .collapse}
    Solución: $-2 \le x\le -1$.
    :::
:::


## Inecuaciones del tipo $\dfrac{P(x)}{Q(x)} \le R(x)$ {#inecuaciones-del-tipo-fracpxqx-le-rx}


Cuando se resuelven este tipo de inecuaciones no hay que caer en el error de \"presuponer\" nada. Intentemos explicarnos mejor con el siguiente ejemplo.

Consideramos la inecuación: $\dfrac{x^2+1}{x-1} \le x$.

::: {#box2 .jxgbox style="width:500px;height:500px;margin:auto;"}
:::
```{ojs}
board2 = JXG.JSXGraph.initBoard('box2', {boundingbox: [-4, 6, 10, -4], axis:true, showCopyright:false, showNavigation:false});
curve2=board2.create('functiongraph', [function(t){ return((t*t+1)/(t-1))}, -10,10]);
p1_2 = board2.create("point",[0,0],{visible:false});
p2_2 = board2.create("point",[1,1],{visible:false});
l1_2 = board2.create("line",[p1_2,p2_2], {fixed:true,strokeColor:"orange"});//'functiongraph',  [function(t){ return(t)}, -10,10]);
ineq = board2.create("inequality",[l1_2]);
i2=board2.create('intersection', [curve2, l1_2, 0],{withLabel:false});
```

Es claro que el punto $x=1$ no es solución, ya que anula al denominador. Entonces, en primer lugar, quitamos el denominador multiplicando ambos miembros por el denominador $x-1$:

$$
\begin{aligned}
x^2+1 & \le x^2-x, \\
1 & \le -x, \\
%\intertext{Multiplicando ambos miembros de la inecuación por $-1$ y la desigualdad se invierte}
-1 & \ge x.\end{aligned}
$$

Parecería entonces que la solución es el conjunto $(-\infty,-1]$. Sin embargo, es fácil comprobar que el punto $x=0$ es solución de la inecuación y, evidentemente, no pertenece al conjunto solución que acabamos de dar. ¿Qué ha pasado entonces? Ha pasado que, en el primer paso que hemos dado (multiplicar ambos miembros de la inecuación por el denominador $x-1$), hemos \"presupuesto\" que $x-1>0$, es decir, que $x>1$. Por lo que el conjunto solución que hemos obtenido por ahora no tiene sentido con la suposición que hemos hecho de $x>1$. Por tanto, como en el caso $x-1>0$ no habría solución, tenemos que contemplar la posibilidad de que $x-1<0$, es decir, de que $x$ fuera menor que $1$. Consideramos este caso ahora, con lo que al multiplicar por el denominador, la desigualdad se invierte.

$$
\begin{aligned}
x^2+1 & \ge x^2-x,\\
1 & \ge -x,\\
x & \ge -1.
\end{aligned}
$$

Por tanto, la solución está formada por los puntos $x$ tales que $x<1$ y además $x \ge -1$. Es decir, el intervalo $[-1,1)$.


::: {#exr-4}
Resuelve cada una de las inecuaciones siguientes.

1.  $\dfrac{2x-3}{x-4} \ge 3$.
    <button id="e4-1" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e4-1 .collapse}
    Solución: $4< x\le 9$.
    :::

2.  $\dfrac{x-1}{x+1} <1$.
    <button id="e4-2" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e4-2 .collapse}
    Solución: $x>-1$.
    :::

3.  $\dfrac{2x^2-4}{2x+1} \ge x-1$.
    <button id="e4-3" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

    ::: {#solucion-e4-3 .collapse}
    Solución: $x<-\dfrac{1}2$ o $x\ge 3$.
    :::
:::


------------------------------------------------------------------------

[Esta página está basada en las transparencias de Jerónimo Alaminos Prats, José Extremera Lizana y Pilar Muñoz Rivas para el Curso Cero de la ETSIIT de la Universidad de Granada. Las representaciones gráficas se han realizado con [JSXGraph](http://jsxgraph.uni-bayreuth.de). El maquetado y las gráficas han sido realizadas por Pedro A. García Sánchez.]{.small}
