---
title: Fracciones algebraicas
title-block-banner: true
lang: es
execute:
  echo: false
format: 
  html: 
    # theme: [night, custom.scss]
    include-in-header: includes-header.html
    fontsize: 1.2em
    toc: true
    page-layout: full
    format-links: true
    html-math-method:
            method: mathjax
            url: "https://cdn.jsdelivr.net/npm/mathjax@4/tex-svg.js"
---

En este documento repasaremos cómo simplificar fracciones algebraicas.


## Simplificaciones elementales


En esta sección vamos a repasar los procedimientos más usuales cuando se simplifican expresiones algebraicas. Comenzamos con un ejemplo en el que, tanto el numerador como el denominador, son de fácil factorización.

Vamos a simplificar la fracción $\frac{4x^5}{2x^3}$. En primer lugar factorizamos numerador y denominador:

$$
\begin{aligned}
\frac{4x^5}{2x^3} &= \frac{2 \cdot 2 \ x^3 \, x^2}{2 \, x^3} \\
%\text{ (y simplificamos los factores comunes $2$ y $x^3$) }
& =\frac{\require{cancel}\cancel{2} \cdot 2 \cancel{x^3} \, x^2}{\cancel{2} \cancel{x^3}}=2x^2.
\end{aligned}
$$

Puedes probarlo tú mismo (observa los paréntesis en el denominador). Usa el siguiente cuadro para simplificar expresiones.

::: {style="width:50%;"}
<textarea id="terminal2" name="terminal" rows="2" cols="80" style="width:100%;margin-bottom:-5px;">
4x^5/(2x^3)
</textarea>
<textarea id="output2" name="terminal" rows="1" cols="80" style="width:100%;"></textarea>
<input name="execute" value="&#x25B6;" onclick="execute(2,'simplify')" type="button" class="btn btn-light btn-sm">
:::


::: {#exr-1}
Simplifica las siguientes fracciones algebraicas.

1.  $\dfrac{6aba^3}{9a^2}$
    [$=\dfrac{2}{3}a^2b$]{#solucion-e1 .collapse}.
    <button id="e1" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

2.  $\dfrac{2x(x-4)}{(x-4)^2y}$
    [$=\dfrac{2 x}{(x-4)y}$]{#solucion-e2 .collapse}.
    <button id="e2" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

3.  $\dfrac{12x^2(3+x)^3}{6x(x+3)}$
    [$=2 x (3+x)^2$]{#solucion-e3 .collapse}.
    <button id="e3" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>
:::

En el siguiente ejemplo constatamos que las factorizaciones no siempre se nos dan hechas. Por ejemplo:

Para simplificar la expresión $\dfrac{ 2x^2+8x}{4x^2-4x}$, en primer lugar, nuevamente, factorizamos numerador y denominador:

$$
\begin{aligned}
\frac{ 2x^2+8x}{4x^2-4x} & =\frac{2x(x+4)}{4x(x-1)} \\
%\text{y simplificamos los factores comunes $2$ y $x$}
& = \frac{2\cancel{x}(x+4)}{4\cancel{x}(x-1)} =\frac{x+4}{2(x-1)}. \end{aligned}
$$

Puedes probarlo tú mismo. Usa el siguiente cuadro para factorizar polinomios.

::: {style="width:50%;"}
<textarea id="terminal3" name="terminal" rows="2" cols="80" style="width:100%;margin-bottom:-5px;">
2x^2+8x
</textarea>
<textarea id="output3" name="terminal" rows="1" cols="80" style="width:100%;"></textarea>
<input name="execute" value="&#x25B6;" onclick="execute(3,'factor');" type="button" class="btn btn-light btn-sm">
:::


:::{#exr-2}

Factoriza y simplifica las siguientes fracciones algebraicas:

1.  $\dfrac{x^2-xy}{xy-y^2}$
    [$=\dfrac{x}{y}$]{#solucion-e4 .collapse}.
    <button id="e4" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

2.  $\dfrac{x^3+x}{2x^2+9x}$
    [$=\dfrac{x^2+1}{2 x + 9}$]{#solucion-e5 .collapse}.
    <button id="e5" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

3.  $\dfrac{4a^2+a}{ab-a^2}$
    [$=\dfrac{4a+1}{b-a}$]{#solucion-e6 .collapse}.
    <button id="e6" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>
:::

## Identidades notables

En algunas expresiones tendremos que utilizar las identidades notables, por lo que vamos a recordarlas.


1.  $(a+b)^2=a^2+2ab+b^2$

2.  $(a-b)^2=a^2-2ab+b^2$

3.  $(a+b)(a-b)=a^2-b^2$

Simplifiquemos la expresión $\frac{x^2+4x+4}{x^2-4}$. Para ello utilizamos que $(x+2)^2=x^2+4x+4$ y que $x^2-4=(x+2)(x-2)$

$$
\begin{aligned}
\frac{x^2+4x+4}{x^2-4}&=\frac{(x+2)^2}{(x+2)(x-2)} \\
%\text{(donde hemos utilizado $(x+2)^2=x^2+4x+2$ y que $x^2-4=(x+2)(x-2)$)}
&=\frac{\cancel{(x+2)}(x+2)}{\cancel{(x+2)}(x-2)}=\frac{x+2}{x-2}.\end{aligned}
$$


:::{#exr-3}
Factoriza y simplifica las siguientes fracciones algebraicas:

1.  $\dfrac{5x^2-5}{x^2-x}$
    [$=\dfrac{5x+5}{x}$]{#solucion-e7 .collapse}.
    <button id="e7" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

2.  $\dfrac{3x^3-3x^2}{6(x^2-2x+1)}$
    [$=\dfrac{x^2}{2x-2}$]{#solucion-e8 .collapse}.
    <button id="e8" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>
:::


## Suma y resta de fracciones algebraicas


En este tipo de operaciones con fracciones algebraicas, al igual que cuando se suman y restan fracciones de números, lo primero que debemos hacer es buscar el mínimo común múltiplo de los denominadores. Lo vemos en el siguiente ejemplo.

Vamos a desarrollar la expresión: $\frac{1}{x-1}+\frac{2x-1}{x^2-1}-\frac{x+2}{x+1}$. Observamos que el m.c.m. de los denominadores es $(x-1)(x+1)=x^2-1$. Así que realizamos la operación de igual forma que con fracciones numéricas. Esto es,

$$
\begin{aligned}
\frac{1}{x-1}+\frac{2x-1}{x^2-1}-\frac{x+2}{x+1}&= \frac{x+1+2x-1-(x+2)(x-1)}{x^2-1}\\
&= \frac{3x-(x^2+x-2)}{x^2-1}=\frac{-x^2+2x+2}{x^2-1}.\end{aligned}
$$


::: {#exr-4}
Desarrolla y simplifica, todo lo posible, las siguientes expresiones algebraicas:

1.  $\dfrac{3x+1}{x}-\dfrac{1}{x^2-x}$
    [$=\dfrac{3x^2-2x-2}{x^2-x}$]{#solucion-e9 .collapse}.
    <button id="e9" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

2.  $x+\dfrac{2x+1}{x-3}$
    [$=\dfrac{x^2-x+1}{x-3}$]{#solucion-e10 .collapse}.
    <button id="e10" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

3.  $\dfrac{1}{2(x-1)}+\dfrac{1}{2(x+1)}$
    [$=\dfrac{x}{x^2-1}$]{#solucion-e11 .collapse}.
    <button id="e11" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

:::

## Producto y cociente de fracciones algebraicas


Al igual que hemos comentado en la sección anterior, la multiplicación y la división de fracciones algebraicas se ejecuta de la misma forma que con fracciones numéricas. Siempre buscaremos la máxima simplificación en el resultado final.

Realicemos el producto $\frac{x+1}{x-1} \cdot \frac{x^2-x}{x^2+2x+1}$. Para ello, multiplicamos numeradores y multiplicamos denominadores, con lo que nos queda:

$$
\begin{aligned}
\frac{x+1}{x-1} \cdot \frac{x^2-x}{x^2+2x+1}&=\frac{(x+1)(x^2-x)}{(x-1)(x^2+2x+1)} \\
%\text{factorizamos en el numerador y en el denominador}
&=\frac{(x+1)\,x\,(x-1)}{(x-1)(x+1)^2} \\
%\text{y simplificamos los factores $x+1$ y $x-1$}
&=\frac{\cancel{(x+1)} \, x \cancel{(x-1)}}{\cancel{(x-1)(x+1)}(x+1)}= \frac{x}{x+1}.\end{aligned}
$$


::: {#exr-5}
Realiza y simplifica las siguientes operaciones con fracciones algebraicas.

1.  $\dfrac{\frac{x-2}{x+2}}{ \frac{x}{(x+2)^2}}$
    [$=\dfrac{x-2}{x+2}\cdot \dfrac{(x+2)^2}{x}=\dfrac{x^2-4}{x}=x-\dfrac{4}x$]{#solucion-e12 .collapse}.
    <button id="e12" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

2.  $\dfrac{2a}{a^2-4} \cdot \dfrac{a+6}{a^2+2a}$
    [$=\dfrac{2(a+6)}{(a+2)^{2}(a-2)}$]{#solucion-e13 .collapse}.
    <button id="e13" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

3.  $\dfrac{\frac{x}{x^2+4x+4} }{ \frac{x+2}{x^2-x}}$
    [$=\dfrac{x}{(x+2)^2}\cdot \dfrac{x^2-x}{x+2}=\dfrac{x^2(x-1)}{(x+2)^3}$]{#solucion-e14 .collapse}.
    <button id="e14" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>
:::


## Racionalización de fracciones algebraicas


La racionalización de fracciones algebraicas consiste en eliminar los posibles radicales que aparezcan en el denominador. Para ello, multiplicaremos tanto en el numerador como en el denominador por el conjugado de este último. En el ejemplo siguiente realizamos esta operación.

En la fracción $\frac{c}{\sqrt{a}-\sqrt{b}}$ vamos a eliminar los radicales del denominador multiplicando en los dos miembros de la fracción por el conjugado del denominador; esto es, multiplicamos por $\sqrt{a}+\sqrt{b}$ y utilizamos una identidad notable que hemos recordado anteriormente. 

$$
\frac{c}{\sqrt{a}-\sqrt{b}} =\frac{c\, (\sqrt{a}+\sqrt{b})}{(\sqrt{a}-\sqrt{b})(\sqrt{a}+\sqrt{b})}= \frac{c\, (\sqrt{a}+\sqrt{b})}{a-b}.
$$



::: {#exr-6}
Racionaliza las siguientes fracciones:

1.  $\dfrac{x}{x-\sqrt{x}}$
    [$=\dfrac{x(x+\sqrt{x})}{x^2-x}$]{#solucion-e15 .collapse}.
    <button id="e15" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

2.  $\dfrac{x+\sqrt{x}}{x-\sqrt{x}}$
    [$=\dfrac{(x+\sqrt{x})^2}{x^2-x}=\dfrac{x+2\sqrt{x}+1}{x-1}$]{#solucion-e16 .collapse}.
    <button id="e16" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>

3.  $\dfrac{x}{\sqrt{x+1}-\sqrt{x-1}}$
    [$=\dfrac{1}{2}x(\sqrt{x+1}+\sqrt{x-1})$]{#solucion-e17 .collapse}.
    <button id="e17" class="btn btn-light btn-sm" onclick="show(this.id);">Solución</button>
:::


------------------------------------------------------------------------

[Esta página está basada en las transparencias de Jerónimo Alaminos Prats, José Extremera Lizana y Pilar Muñoz Rivas para el Curso Cero de la ETSIIT de la Universidad de Granada. Las simplificaciones algebraicas están hechas con [Algebrite](http://algebrite.org)]{.small}

